#!/bin/bash
# Shell script that handles allowing a single serial port to function as both a sink and a source
if [ -e /tmp/fifo_source ]
then
  sudo rm /tmp/fifo_source
fi
if [ -e /tmp/fifo_sink ]
then
  sudo rm /tmp/fifo_sink
fi
mkfifo /tmp/fifo_source
mkfifo /tmp/fifo_sink

stty -F /dev/ttyS4 115200 cs8 -parenb -cstopb -hupcl crtscts -ixon -ixoff -ixany -icanon -echo -isig -iexten -opost -onlcr icrnl ocrnl

socat -u /tmp/fifo_sink - | sudo socat - /dev/ttyS4 | socat -u - /tmp/fifo_source
